displayName: Test_MS
testPlan: quick_test.jmx
description: Run test against microsoft.com
engineInstances: 1
testId: faed4cd5-c6cc-4925-b4dc-87d4422e94b4
testType: JMX
splitAllCSVs: False
failureCriteria: []
env:
- name: domain
  value: microsoft.com
- name: protocol
  value: https
- name: threads_per_engine
  value: 2
- name: ramp_up_time
  value: 60
- name: duration_in_sec
  value: 60
autoStop:
  errorPercentage: 90
  timeWindow: 60
