name: main

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az --version
          az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.location }}
          az deployment group create --resource-group ${{ parameters.resourceGroupName }} --template-file ${{ parameters.bicepPath }} -n "${{ parameters.deploymentName }}"
          loadTestId=$(az deployment group show -g ${{ parameters.resourceGroupName }} -n "${{ parameters.deploymentName }}" --query properties.outputs.load_test_id.value)
          echo  "[task.setvariable variable=TF_OUT_LOAD_TEST_ID;]$loadTestId"
