name: main

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Builds and pushes an image up to your Azure Container Registry
      - name: Bicep Deployment
        run: |
          az --version
          az group create --name rg-loadtst-demo-weu-bicep --location westeurope
          az deployment group create --resource-group rg-loadtst-demo-weu-bicep --template-file bicep/loadtest.bicep -n "gh-deployment"
          loadTestId=$(az deployment group show -g rg-loadtst-demo-weu-bicep -n "gh-deployment" --query properties.outputs.load_test_id.value)
