trigger: none

parameters:
  - name: infraTechnology
    type: string
    default: terraform
    values:
      - terraform
      - bicep

variables:
  - template: variables.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: terraform.yml
    parameters:
      terraformVersion: $(terraformVersion)
      terraformPath: $(terraformPath)
      serviceConnection: $(serviceConnection)
      containerName: $(terraformContainerName)
      storageAccountName: $(terraformStorageAccountName)
      resourceGroupName: $(terraformResourceGroupName)
      secrets: [ AZURE_DEVOPS_PAT ]
      action: destroy