trigger: none

variables:
  - template: variables.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
  - ${{ if eq(parameters.infraTechnology, 'terraform') }}:
    - template: terraform.yml
      parameters:
        terraformVersion: $(terraformVersion)
        terraformPath: $(terraformPath)
        serviceConnection: $(serviceConnection)
        containerName: $(terraformContainerName)
        storageAccountName: $(terraformStorageAccountName)
        workspace: ${{ variables.saltVar }}
        useWorkspace: ${{ parameters.useWorkspace }}
        resourceGroupName: $(terraformResourceGroupName)
        action: destroy

  - ${{ if eq(parameters.infraTechnology, 'bicep') }}:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        useGlobalConfig: false
        inlineScript: |
          az --version
          az group delete --name $(bicepResourceGroupName) --yes