trigger:
  - "*"

variables:
  - template: variables.yml
  - group: build

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: terraform.yml
    parameters:
      terraformVersion: $(terraformVersion)
      terraformPath: $(terraformPath)
      serviceConnection: $(serviceConnection)
      containerName: $(terraformContainerName)
      storageAccountName: $(terraformStorageAccountName)
      resourceGroupName: $(terraformResourceGroupName)
      secrets: [ AZURE_DEVOPS_PAT ]