trigger:
  - "*"

variables:
  - template: variables.yml
  - group: build

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: terraform.yml
    parameters:
      terraformVersion: $(terraformVersion)
      terraformPath: $(terraformPath)
      serviceConnection: $(serviceConnection)
      containerName: $(terraformContainerName)
      storageAccountName: $(terraformStorageAccountName)
      resourceGroupName: $(terraformResourceGroupName)
      env:
        AZDO_ORG_SERVICE_URL: https://dev.azure.com/jasojohnson
        AZDO_PERSONAL_ACCESS_TOKEN: $(PAT)
        AZURE_DEVOPS_EXT_PAT: $(PAT)
      secrets:
        AZURE_DEVOPS_PAT: PAT