trigger:
  - "*"

parameters:
  - name: infraTechnology
    type: string
    default: terraform
    values:
      - terraform
      - bicep

variables:
  - template: variables.yml

pool:
  vmImage: "ubuntu-latest"

steps:
  - ${{ if eq(parameters.infraTechnology, 'terraform') }}:
    - template: terraform.yml
      parameters:
        terraformVersion: $(terraformVersion)
        terraformPath: $(terraformPath)
        serviceConnection: $(serviceConnection)
        containerName: $(terraformContainerName)
        storageAccountName: $(terraformStorageAccountName)
        resourceGroupName: $(terraformResourceGroupName)

  - ${{ if eq(parameters.infraTechnology, 'bicep') }}:
    - template: bicep.yml
      parameters:
        bicepPath: $(bicepPath)
        serviceConnection: $(serviceConnection)
        resourceGroupName: $(bicepResourceGroupName)
        location: westeurope

  - template: loadTests.yml
    parameters:
      testsPath: src/loadtests
      loadTestResourceName: $(TF_OUT_LOAD_TEST_NAME)