trigger:
  - "*"

parameters:
  - name: infraTechnology
    type: string
    default: terraform
    values:
      - terraform
      - bicep
  - name: salt
    default: ''
  - name: useWorkspace
    default: false
    type: boolean

variables:
  - template: variables.yml
  - name: saltVar
    ${{ if eq(parameters.useWorkspace, true) }}:
      value: ${{ parameters.salt }}
    ${{ else }}:
      value: ''

pool:
  vmImage: "ubuntu-latest"

steps:
  - ${{ if eq(parameters.infraTechnology, 'terraform') }}:
    - template: terraform.yml
      parameters:
        terraformVersion: $(terraformVersion)
        terraformPath: $(terraformPath)
        serviceConnection: $(serviceConnection)
        containerName: $(terraformContainerName)
        storageAccountName: $(terraformStorageAccountName)
        workspace: ${{ variables.saltVar }}
        useWorkspace: ${{ parameters.useWorkspace }}
        resourceGroupName: $(terraformResourceGroupName)
        env:
          TF_VAR_branch: ${{ variables.saltVar }}

  - ${{ if eq(parameters.infraTechnology, 'bicep') }}:
    - template: bicep.yml
      parameters:
        bicepVersion: $(bicepVersion)
        bicepPath: $(bicepPath)
        serviceConnection: $(serviceConnection)
        containerName: $(bicepContainerName)
        storageAccountName: $(bicepStorageAccountName)
        workspace: ${{ variables.saltVar }}
        useWorkspace: ${{ parameters.useWorkspace }}
        resourceGroupName: $(bicepResourceGroupName)
        env:
          TF_VAR_branch: ${{ variables.saltVar }}